// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDnvwdybHE-0ZjgFEH9en3wqhGP1jkypA',
    appId: '1:427803240492:web:67980306ce21a668080989',
    messagingSenderId: '427803240492',
    projectId: 'pixie-image-app',
    authDomain: 'pixie-image-app.firebaseapp.com',
    storageBucket: 'pixie-image-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-oi6gu2HPFnqAOc0zz2m--SRjYCnmu0',
    appId: '1:427803240492:android:5823fb15e64cf493080989',
    messagingSenderId: '427803240492',
    projectId: 'pixie-image-app',
    storageBucket: 'pixie-image-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ebrorsLzO0xYMunXzlpOyAHPlu25bhg',
    appId: '1:427803240492:ios:a0097208b17f965e080989',
    messagingSenderId: '427803240492',
    projectId: 'pixie-image-app',
    storageBucket: 'pixie-image-app.appspot.com',
    iosClientId: '427803240492-cg3k4ikeeg18mfgruh3ngec84ila0ulr.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ebrorsLzO0xYMunXzlpOyAHPlu25bhg',
    appId: '1:427803240492:ios:a0097208b17f965e080989',
    messagingSenderId: '427803240492',
    projectId: 'pixie-image-app',
    storageBucket: 'pixie-image-app.appspot.com',
    iosClientId: '427803240492-cg3k4ikeeg18mfgruh3ngec84ila0ulr.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixie',
  );
}
